### ISSUE TITLE
部分系统上IP地址识别错误，导致SSR链接生成有问题，手动修改即可

### ISSUE THREAD

**Issue by Sunsnok** [FunctionClub/SSR-Bash-Python#1]
可否请教如何修改

**Comment by YLWS-4617** [comment]
只需要自己填写ip的时候，填写真实VPS ip就好了，不用那个ssr:// 链接

**Comment by KiritoMiao** [comment]
If you still have any problem like this, please report to https://github.com/breakwa11/shadowsocks-rss

**Comment by zyh001** [comment]
@openviso 在1024M以内是以M为单位，超过1024M以上即为G
