### ISSUE TITLE
关于流量控制清空的问题

### ISSUE THREAD

**Issue by smusicsanshu** [FunctionClub/SSR-Bash-Python#12]
大佬好：问一个关于，SSR-Bash-Python **流量控制**的问题：

>是每个用户 30天后自动清空开始重新计算吗？

比如：A用户  5月2号开始计算流量，到6月2号，自动清空流量并重新计算
           B用户   5月15号开始计算流量，到6月15号，自动清空流量并重新计算

> 不管什么时候开始计算，都是每月1号清空结算

> 单个用户到期之后，手动清空单个用户的流量，

**Comment by KiritoMiao** [comment]
https://www.ixh.me/2017/05/function-club-stop/

**Comment by smusicsanshu** [comment]
你好，现在开始维护了吗？
