### ISSUE TITLE
运行卸载脚本报错

### ISSUE THREAD

**Issue by jianguooo** [FunctionClub/SSR-Bash-Python#13]
--2017-05-24 09:51:57--  (try: 3)  https://raw.githubusercontent.com/FunctionClub/SSR-Bash-Python/master/uninstall.sh
Connecting to raw.githubusercontent.com|151.101.72.133|:443...

**Comment by KiritoMiao** [comment]
Function Club 无限期停更说明
https://www.ixh.me/2017/05/function-club-stop/
