### ISSUE TITLE
新增的auth_chain_a协议无法使用

### ISSUE THREAD

**Issue by AENeuro** [FunctionClub/SSR-Bash-Python#14]
method: none
protocol: auth_chain_a
obfs: plain
服务端的日志报错：server_pool.py:166 IPV4 obfs plugin [auth_chain_a] not supported

**Comment by YLWS-4617** [comment]
请同时升级 Shadowsocksr 服务端。
升级方法：
cd /usr/local/shadowsocksr
git pull

**Comment by dansenpir** [comment]
@AENeuro Quando você definir qual ferramenta irá usar na criação do seu site e começar a estudar, aí tudo fará sentido.

**Comment by AENeuro** [comment]
@dansenpir thanks bro
