### ISSUE TITLE
安装Libsodium失败

### ISSUE THREAD

**Issue by lynnhou** [FunctionClub/SSR-Bash-Python#16]
首先说声抱歉，我去掉了地区验证，以便安装在国内的华为云，但是安装的时候出现安装Libsodium失败的情况，不知道如何解决。国内安装仅仅作为个人使用，不做商业用途，话说回来，华为云那么慢，就算是想商业用途也没有有可能啊

**Comment by YLWS-4617** [comment]
其实我们设置国内验证只是为了防止将SSR部署在国内服务器进行免流而已。Libsodium出错了，请给下错误截图，方便排查信息。

**Comment by lynnhou** [comment]
公司限制太多，甚至阻碍工作，要突破下限制，等下我安装下给你看看错误截图

**Comment by lynnhou** [comment]
![tim 20170626110633](https://user-images.githubusercontent.com/28432156/27523351-3473d788-5a5f-11e7-9bf0-37f176365f1d.png)出错的情况如图所示

**Comment by YLWS-4617** [comment]
无法下载 Libsodium 。这是国内服务器与国外服务器的线路问题。因为本地的华为云在国内，无法链接到Libsodium下载服务器。 如果你想跳过，你可以把安装 Libsodium的这段代码删掉，只有chacha20系和sala20系加密方式无法使用，其他功能都正常。

**Comment by lynnhou** [comment]
好的，谢谢指教！我现在就是不用chacha20，反正也没啥影响。



发自我的小米手机
在 iPatrick <notifications@github.com>，2017年6月26日 上午11:07写道：

无法下载 Libsodium 。这是国内服务器与国外服务器的线路问题。因为本地的华为云在国内，无法链接到Libsodium下载服务器。 如果你想跳过，你可以把安装 Libsodium的这段代码删掉，只有chacha20系和sala20系加密方式无法使用，其他功能都正常。
